# Generated by Django 4.2.7 on 2023-11-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='data',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pereval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='the_pass.pereval_added'),
        ),
    ]
