# Generated by Django 4.2.7 on 2023-11-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_pass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='pereval',
        ),
        migrations.AddField(
            model_name='pereval_added',
            name='photos',
            field=models.ManyToManyField(to='the_pass.photo'),
        ),
        migrations.AlterField(
            model_name='pereval_added',
            name='coords',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_pass.coords'),
        ),
    ]
